### ISSUE TITLE
Question Regarding Node Booting and Installation Loop

### ISSUE THREAD

**Issue by savager** [khuedoan/homelab#10]
Forgive as this seems like a generally novice question, but I was able to get a small display hooked up to one of my nodes to verify/review the pxe booting. To my surprise I had successfully configured my router and modified the repo. But I am not aware of the process of the OS installation.

My installation seems to run over and over again.

```
Installing boot loader
..
Performing post-installation setup tasks
.
Configuring installed system
................
Writing network configuration
.
Creating users
Configuring addons
Executing com_redhat_kdump addon
Executing org_fedora_oscap addon
..
Generating intramfs
...
Storing configuration files and kickstarts
.
Running post-installation scripts
```

Then it reboots, loads rocky from PXE, and begins the process again.

Does it install to the nvme every time it boots? Am I supposed to disable the PXE server and boot to the OS after installation? Perhaps one of my generated boot files isn't proper, where should I look. Thanks for all your help!

**Comment by khuedoan** [comment]
Look like it installed to your SSD successfully and you're on the right track, however the boot order in your BIOS might need some tweaks:

- If powered on manually or reboot: prefer booting from disk
- If powered on via WoL: prefer network boot

You can refer to this section for my specific set up, but your BIOS might be different: https://homelab.khuedoan.com/deployment/prerequisites.html#bios-setup (I probably need to make it clearer in the document)

**Comment by savager** [comment]
Well, actually you did document this I just don't know that my bios supports these BIOS settings. They're MSI H410 motherboards and are very consumer. I do see that I enabled "Resume by onboard Intel LAN" which seems like WOL. I will try other configurations. Thanks again for the rapid response.

**Comment by khuedoan** [comment]
I just check the MSI motherboard on my workstation and I can't find similar settings, I think you can try the following:

- Set the boot order to:
  1. Hard drive
  2. Network
- Manually wipe the drives on all servers (or just delete the Rocky Linux/Ubuntu boot entry)

From now on it will only boot using the PXE server if no operating system found.

Thinking about this again maybe this is even better because it prevent us from accidentally wipe Rocky Linux 🤔

**Comment by savager** [comment]
That, is a really good idea! I will wipe the drives and attempt it right now.

**Comment by savager** [comment]
Just to confirm this solution did work successfully. Thanks!

**Comment by khuedoan** [comment]
Awesome!
