### ISSUE TITLE
Failed smoke tests

### ISSUE THREAD

**Issue by Jsakkos** [khuedoan/homelab#104]
### Describe the bug

Smoke test at end of make sequence fails all 5 tests (single node cluster). Both dex and renovate are showing ```CreateContainerConfigError``` when I look at the pods with k9s.

- [X] I have read the document

### To reproduce

1. ```make tools```
[log.txt](https://github.com/khuedoan/homelab/files/10611998/log.txt)

2. ```make configure```
3. Fill out details.
4. ```make```

### Expected behavior

The tests should pass, since all of the pages (except for home) are up and running.

### Additional context

Dell Optiplex Micro 5060, 16 GB RAM, 1 TB NVME.

**Comment by Jsakkos** [comment]
This is related to an issue with hajimari. Commenting out global bookmarks section of apps/hajimari/values.yaml fix hajimari and allowed the tests to pass. 

```    
hajimari:
  env:
    TZ: America/Los_Angeles
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    #globalBookmarks:
     # - group: Homelab
     #   bookmarks:
     #     - name: Documentation
     #       url: https://homelab.toolstowelsandfroods.com
     #     - name: Public GitHub repository
     #       url: https://github.com/khuedoan/homelab
     # - group: Managed services
     #   bookmarks:
     #     - name: Terraform Cloud
     #       url: https://app.terraform.io
     #     - name: Cloudflare
     #       url: https://dash.cloudflare.com

**Comment by khuedoan** [comment]
Thanks, this should be fixed in https://github.com/khuedoan/homelab/commit/0e84f90a8ae161a8f12f88424929204c8e843cc2, please re-open if you still have the issue.
