### ISSUE TITLE
「automatic_upgrade: Install packages for automatic upgrade」error: Could not import the dnf python module using /usr/bin/python3 

### ISSUE THREAD

**Issue by lianghuiyuan** [khuedoan/homelab#106]
**The error:**
![image](https://user-images.githubusercontent.com/8090998/232013569-70274b44-cadd-42fb-8c08-07277cc90f2c.png)

`Could not import the dnf python module using /usr/bin/python3 (3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])
fatal: [metal3]: FAILED! =&gt; {
    "changed": false,
    "results": []
}`

**Controller PC:** Ubuntu: 18.04
**python3:** 3.6.9 
**python2:** 2.7.17
**Tools Container:** nix-shell (image: nixos/nix)
![image](https://user-images.githubusercontent.com/8090998/232020756-a11f59ea-e036-4313-ac95-9e0f3f450ef1.png)

**Server masters/works:** Ubuntu Server 22.04

Anyone can help me?
I tried to follow "[How To Install python3-dnf on Ubuntu 22.04](https://installati.one/install-python3-dnf-ubuntu-22-04/)"  and some other ways to fix the problems, But no help.
![image](https://user-images.githubusercontent.com/8090998/232020640-6fecd0aa-fa99-4466-a5dc-2452ccc40150.png)

**Comment by khuedoan** [comment]
Are you using the included automated OS installer? It's Fedora not Ubuntu, and you don't need to install the OS manually.

**Comment by khuedoan** [comment]
If you really want to use Ubuntu you can checkout this fork https://github.com/linhng98/mess-around/tree/master/metal/roles/pxe_server

**Comment by khuedoan** [comment]
Closing since Ubuntu is not the officially supported distro
