### ISSUE TITLE
zerotier

### ISSUE THREAD

**Issue by dotdiego** [khuedoan/homelab#107]
Hello,

Quick question about Zerotier.

How do you access internal services or other pods using Zerotier network ?

It seems I can only access the pod running zerotier and not the whole cluster.

**Comment by khuedoan** [comment]
The route was hard coded here https://github.com/khuedoan/homelab/blob/96a968bc9f7856382df0fd6eade8cce4ef7f5448/external/main.tf#L12, you can change it manually for now

**Comment by dotdiego** [comment]
So with this setup

Node : 192.168.1.10
Node : 192.168.1.11
Node : 192.168.1.12 <-- Zerotier pods run on this node
NAS: 192.168.1.100

With the route 192.168.1.0/24 via 10.147.17.1 (address of my zt interface on my pod). 

Should I be able to ping the NAS which isn't part of the cluster, or any node or service that is in the cluster ?

**Comment by khuedoan** [comment]
Do you have this part?

https://github.com/khuedoan/homelab/blob/96a968bc9f7856382df0fd6eade8cce4ef7f5448/platform/zerotier/deployment.yaml#L46-L50

**Comment by dotdiego** [comment]
Yes I have this part.

But here's what i have :
$POD_IP = 10.42.195.228

ip route result :
```
10.147.17.0/24 dev zt0 proto kernel scope link src 10.147.17.1
169.254.1.1 dev eth0 scope link
```

That's why the export PHY_IFACE was not set and I had to change the command to get the eth0

From shell in zerotier-router pod : PING 192.168.1.100 works. 
From linux box joined to the zerotier network (and accepted in Zerotier Central) ping 192.168.1.100 doesn't work.

Even with the route set as 192.168.1.0/24 via 10.147.17.1

**Comment by khuedoan** [comment]
Also do you have a mobile device to try, just to make sure the problem is not because of the Linux client.

**Comment by dotdiego** [comment]
`ip route show` result (`ip route a` doesn't seem to exist)

```
default via 169.254.1.1 dev eth0
10.147.17.0/24 dev zt0 proto kernel scope link src 10.147.17.1
169.254.1.1 dev eth0 scope link
```

I tried from a windows client :

 `ping -I zt0 192.168.1.100` i tried it with node address too

```
PING 192.168.1.100 (192.168.1.100) from 10.147.17.1 zt0: 56(84) bytes of data.
From 10.147.17.1 icmp_seq=1 Destination Host Unreachable
```

**Comment by khuedoan** [comment]
Oops sorry I mean `ip a`

**Comment by dotdiego** [comment]
I think the issue comes from having Calico installed. I'll look more into it. On how it affects the gateway it sets automatically on pods (the 169.254.1.1 IP)
