### ISSUE TITLE
new fresh deployment only those pods run

### ISSUE THREAD

**Issue by MCP-LTS** [khuedoan/homelab#117]
Hello as you can see in the k9s screenshot after a fresh deployment only those pods fires any suggestions?
![image](https://github.com/khuedoan/homelab/assets/88507785/ad2c5dfc-617b-42aa-86f6-3c09c648e2c2)

make test too many errors

**Comment by khuedoan** [comment]
You can remove the blog from `./apps/blog`, it's just [my personal website](github.com/khuedoan/blog) and you probably don't need it.

**Comment by MCP-LTS** [comment]
i changed master and worker info but since master is in virtualbox needed enp0s3 in prod.yml and real hardware eno1. thats why i got too few pods. im still trying to make it work. hope helps someone in similar situation.
