### ISSUE TITLE
Route53 instead of cloudflared?

### ISSUE THREAD

**Issue by KalebSchmidlkofer** [khuedoan/homelab#124]
Is it possible to use Route53 instead of cloudflared?

**Comment by khuedoan** [comment]
They have different purposes:

- Route53: DNS provider, similar to Cloudflare DNS 
- `cloudflared` (Cloudflare Tunnel): expose services to the internet without port forwarding

If you want to change DNS provider, you can change it in External DNS config:

https://github.com/khuedoan/homelab/blob/674e7e650553e665cd496760ea271a5bd20baf4a/system/external-dns/values.yaml#L1-L2

If you want to change tunnel provider, there are some alternatives like Tailscale Funnel, Ngrok, Inlets, etc.

**Comment by khuedoan** [comment]
See also:

- https://homelab.khuedoan.com/how-to-guides/alternate-dns-setup
- https://homelab.khuedoan.com/how-to-guides/expose-services-to-the-internet

**Comment by KalebSchmidlkofer** [comment]
Thank you.
