### ISSUE TITLE
System-upgrade was removed

### ISSUE THREAD

**Issue by ClashTheBunny** [khuedoan/homelab#129]
Just delete this line?

https://github.com/khuedoan/homelab/blob/e1c276e403a0196dce52fe9c94d681988afcc96e/docs/how-to-guides/single-node-cluster-adjustments.md?plain=1#L22C17-L22C17

**Comment by khuedoan** [comment]
Thank you, updated in https://github.com/khuedoan/homelab/commit/bd0d7b556d3ed4440d6cbff146a31cc04ef47c77
