### ISSUE TITLE
Feature proposal: automating alert and event response using robusta

### ISSUE THREAD

**Issue by aantn** [khuedoan/homelab#13]
Hi, I'd like to suggest using robusta (https://github.com/robusta-dev/robusta) for automating the response to alerts and other events in your cluster. It's a runbook automation platform for Kubernetes with built-in automations for common errors and quality of life automations like marking application updates on your Grafana graphs.

Robusta can also be installed with a built-in Prometheus/Grafana/alertmanager stack (based on kube-prometheus-stack) if you want an all in one monitoring solution.

I'm the maintainer and happy to answer any questions. It's worth pointing out that we also have a SaaS platform which probably is *not* relevant for this, but it's disabled by default and everything will work without it. (If you are interested though, it's free.)

**Comment by khuedoan** [comment]
Seems like only Slack is supported and I use Matrix. Closing for now.
