### ISSUE TITLE
Add idm_admin creation to kanidm admin reset script?

### ISSUE THREAD

**Issue by ClashTheBunny** [khuedoan/homelab#130]
https://github.com/khuedoan/homelab/blob/e1c276e403a0196dce52fe9c94d681988afcc96e/scripts/kanidm-reset-admin-password#L5

```
kanidm login -D admin
kanidm service-account credential generate -D admin idm_admin
```

**Comment by khuedoan** [comment]
Thanks for the suggestion, I have updated the script to allow password reset for any account https://github.com/khuedoan/homelab/commit/f3e3fa22ec7c9c126a5473d4cb54618266d8c6bd, e.g.:

```
./scripts/kanidm-reset-password idm_admin
./scripts/kanidm-reset-password khuedoan
```

> Note: resetting a user account also removes passkeys and TOTP (if any), so for user account `kanidm person credential create-reset-token` is a better choice.
