### ISSUE TITLE
Contact Point of AlertManager is absent

### ISSUE THREAD

**Issue by longbowapache** [khuedoan/homelab#133]
It seems that contact point of grafana is configured in values.yaml of grafana. However, the alert rules are configured in AlertManger and the alerts are not be notified. Is this a bug or intended design?

**Comment by longbowapache** [comment]
> That's probably a bug, I'm still refactoring the alerting system. Could you please try sending an alert manually in Grafana (Alerting -> Contact points -> ntfy)?

Sending an alert from grafana is ok now.
![image](https://github.com/khuedoan/homelab/assets/1762328/9ef0e4ac-3dba-4d58-abe7-f6e9cfba9684)

The problem is that the ntfy notification policy is belongs to Grafana, not AlertManager:
![image](https://github.com/khuedoan/homelab/assets/1762328/a74c6939-5716-4064-b0b9-8cf6d9fd9a8a)

So, AlertManager's alert is delivered to null.
![image](https://github.com/khuedoan/homelab/assets/1762328/15ed65c7-ba88-416e-8a65-431323ac6a0a)

**Comment by khuedoan** [comment]
Ah right, thank you! I've been experimenting with both Grafana Alerting and Alertmanager, and I need to decide on using just one (my cluster is a bit messy right now to reproduce the issue - I'm planning to rebuild it in a few days though).

I haven't made a decision yet, but I'm now leaning towards yanking Grafana Alerting and only use Alertmanager (if so I'll need to replace the ntfy-relay from grafana-to-ntfy to [something else for Alertmanager](https://docs.ntfy.sh/integrations))

**Comment by longbowapache** [comment]
Thank you! and looking forward to your work!

**Comment by khuedoan** [comment]
There are some WIP if you're interested:

- WIP generic webhook transformer https://github.com/khuedoan/webhook-transformer
- WIP Transform Alertmanger to ntfy using the above project as a sidecar: https://github.com/khuedoan/homelab/compare/master...alertmanager2ntfy

![image](https://github.com/khuedoan/homelab/assets/27996771/0799ced8-79d9-47dd-ad92-fa4c4679309c)
