### ISSUE TITLE
Getting errors on bootstrap phase with ApplicationSets

### ISSUE THREAD

**Issue by romelBen** [khuedoan/homelab#140]
I'm currently running into an issue of K8s ApplicationSets. This is probably stemming from Gitea trying to work but fails. The error that pops up for me is the following error in the pod itself:
```
│     Message:               error while checking out repo: Error during fetching repo: `git fetch origin master --tags --force --prune` failed exit status 128: fatal: could not read Username for 'https://github.com': No such device or address
│     Reason:                ApplicationGenerationFromParamsError                                                  
│     Status:                True                                                                                                     
│     Type:                  ErrorOccurred                                                                                   
│     Last Transition Time:  2024-02-11T09:41:10Z                                                                  
│     Message:               error while checking out repo: Error during fetching repo: `git fetch origin master --tags --force --prune` failed exit status 128: fatal: could not read Username for 'https://github.com': No such device or address
```
Since my repository is private, I am running through having my pods having `git` on them but I guess I'm going by this the wrong route. I would appreciate any help so I can resolve this error.

**Comment by khuedoan** [comment]
Private repo is not supported, please make a public fork.

The whole goal of using GPL is everyone can use it freely and I can learn and get the changes from other people's fork. If you're the only user of your homelab you probably don't _have_ to make it public (although I kinda wish that I went with AGPL íntead of GPL), but there's no support.

Please feel free to reopen this issue if you still have the same problem after making the fork public.
