### ISSUE TITLE
Add Infro PR Checks?

### ISSUE THREAD

**Issue by colethienes** [khuedoan/homelab#143]
I noticed that this repo uses Argo CD, and I thought I’d let you know that I recently released a Github app called Infro that several companies use internally that allows Argo CD users to preview Kubernetes changes in Github pull requests before they merge. I’m providing it for free to open source projects ([here’s](https://github.com/broersma-forslund/homelab/pull/158#issuecomment-1962289857) an example in the wild). [Here’s](https://medium.com/@colethienes/argocd-pull-request-checks-c863190c5f8c?source=friends_link&sk=2eda79520de33483591448c6dfe8d284) a setup guide with links to documentation. It’s in early stages, so I’m sure there will be warts. All feedback is welcome!

**Comment by khuedoan** [comment]
Thanks for the offer but I mainly use Gitea, GitHub is essentially just my public mirror.
Also I [already have this feature in my homelab](https://github.com/khuedoan/homelab/blob/master/.woodpecker/helm-diff.yaml).
