### ISSUE TITLE
Where to buy this mini PC?

### ISSUE THREAD

**Issue by AielloChan** [khuedoan/homelab#15]
**NEC SFF PC-MK26ECZDR**

I searched amazon.jp and amazon.com, but can't find.

**Comment by khuedoan** [comment]
TBH I don't know, I bought them used from a reseller on Facebook :stuck_out_tongue:

**Comment by Guik** [comment]
You can look for some refurbished computer.
I search for some Dell Optiplex Micro based on i5 8500t and found some 5060 with 8Gb and 256Gb ssd for around 250euros.
This is low tdp cpu with 6 cores, you can go to up 32Gb ram and there is a free space for a sata ssd. 

You can track on Ebay for example: https://www.ebay.fr/sch/i.html?_nkw=optiplex+8500t&_sacat=0

Have fun !

**Comment by khuedoan** [comment]
One thing to keep in mind is that if you want to take advantage of HA and rolling upgrade for nodes, you should use multiple lower-spec machines rather than a single high-spec one.

**Comment by khuedoan** [comment]
Closing since I don't know where to buy the exact model, but any modern small form factor PC should work fine.
