### ISSUE TITLE
dex secret not found

### ISSUE THREAD

**Issue by donydonald1** [khuedoan/homelab#155]
hello @khuedoan 
i am a big fan of this and I have been trying to get work like this a week now but I have a little issue trying to make mine work. hoping you could help.
external secret didn't create a secret for dex.
please help
```shell
)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dex
    Optional:    false
  kube-api-access-wl57w:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason  Age                    From     Message
  ----     ------  ----                   ----     -------
  Warning  Failed  60m (x12 over 62m)     kubelet  Error: secret "dex-secrets" not found
  Normal   Pulled  2m31s (x278 over 62m)  kubelet  Container image "ghcr.io/dexidp/dex:v2.38.0" already present on machine ```

**Comment by khuedoan** [comment]
Hi, `dex-secrets` is created by https://github.com/khuedoan/homelab/blob/master/platform/dex/templates/secret.yaml, could you please post the output of:

```sh
kubectl describe -n dex externalsecret dex-secrets
```

**Comment by donydonald1** [comment]
```shell
+ kubectl describe -n dex externalsecret dex-secrets
Name:         dex-secrets
Namespace:    dex
Labels:       argocd.argoproj.io/instance=dex
Annotations:  <none>
API Version:  external-secrets.io/v1beta1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2024-04-18T09:48:36Z
  Generation:          1
  Resource Version:    51172
  UID:                 94eb9cd1-310b-4a3d-8574-7ed4b326de5c
Spec:
  Data:
    Remote Ref:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  kanidm.dex
      Metadata Policy:      None
      Property:             client_id
    Secret Key:             KANIDM_CLIENT_ID
    Remote Ref:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  kanidm.dex
      Metadata Policy:      None
      Property:             client_secret
    Secret Key:             KANIDM_CLIENT_SECRET
    Remote Ref:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  dex.grafana
      Metadata Policy:      None
      Property:             client_secret
    Secret Key:             GRAFANA_SSO_CLIENT_SECRET
    Remote Ref:
      Conversion Strategy:  Default
      Decoding Strategy:    None
      Key:                  dex.gitea
      Metadata Policy:      None
      Property:             client_secret
    Secret Key:             GITEA_CLIENT_SECRET
  Refresh Interval:         1h
  Secret Store Ref:
    Kind:  ClusterSecretStore
    Name:  global-secrets
  Target:
    Creation Policy:  Owner
    Deletion Policy:  Retain
    Name:             dex-secrets
Status:
  Conditions:
    Last Transition Time:  2024-04-18T09:48:36Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                    From              Message
  ----     ------        ----                   ----              -------
  Warning  UpdateFailed  4m40s (x24 over 109m)  external-secrets  error retrieving secret at .data[0], key: kanidm.dex, err: secrets "kanidm.dex" not found 
  ```
  
  this is also affecting other deployment as well and for some reasons none of the secrets generated works when trying to login to the deployments 
  
  ```shell
woodpecker          pre-install-agent-secret-check-jsqrs                     0/1     Completed                    0                75m
woodpecker          woodpecker-agent-5b6945cc7b-8c49l                        0/1     CrashLoopBackOff             19 (2m41s ago)   75m
woodpecker          woodpecker-agent-5b6945cc7b-nrmmf                        0/1     CrashLoopBackOff             19 (2m52s ago)   75m
```

**Comment by kikokikok** [comment]
Same problem for me, I think the 
kanidm.dex key is never creqted in the global-secrets ClusterSecretStore
<img width="1024" alt="Screenshot 2024-05-05 at 14 17 06" src="https://github.com/khuedoan/homelab/assets/1577981/1f0f08be-2233-41d2-a010-ba86d1dd9d6c">

**Comment by khuedoan** [comment]
`kandim.dex` should be created by default in the post install script, could you try running `make post-install` manually?

**Comment by kikokikok** [comment]
Well the postscript fails when calling the reset of users with the python k8s client. It doesn't return the expected json payload on the stdout as expected which causes an error on json deserialization. 
When executing with a remote ssh into the container, I see the json paylod

**Comment by numpythuckles** [comment]
Also seeing it. 

`bash-5.2#./scripts/hacks

Traceback (most recent call last):
  File "/home/sysops/homelab/./scripts/hacks", line 256, in <module>
    main()
  File "/home/sysops/homelab/./scripts/hacks", line 253, in main
    setup_kanidm_oauth_app(app['name'], app['redirect_uri'])
  File "/home/sysops/homelab/./scripts/hacks", line 196, in setup_kanidm_oauth_app
    client_secret = json.loads(subprocess.run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by numpythuckles** [comment]
Was running into the same JSON decode error on the `reset_kanidm_account_password` function. 

Ran `./scripts/hacks` outside of nix was able to create `global-secrets` for:

```
gitea.renovate
gitea.woodpecker
```
Renovate was also able to create its own `renovate-secret` afterwards and began submitting PRs to Git. 

Still not seeing any `kanidm.*` in `global-secrets`. Working on it.

**Comment by numpythuckles** [comment]
Oddly enough, I think the kanidm API is dead:


### **Attempting to log into kanidm via CLI after running `./scripts/hacks`:**
```
$ kanidm login --name admin --url https://auth.<DOMAIN>.com
2024-06-28T02:42:26.715208Z  WARN kanidm_client: Mismatched client and server version - features may not work, or other unforeseen errors may occur. server_version="1.1.0-rc.16" client_version="1.3.0-dev"
Enter password: 
2024-06-28T02:43:16.362338Z ERROR kanidm_cli::session: Unable to retrieve jwk from server err=Http(404, None, "missing_kopid")
```


### **Attempting to restart kanidm server in container after running `./scripts/hacks`:**

```
$kubectl exec --stdin --tty kanidm-0 -n kanidm -- kanidmd server
Ignoring env var KANIDM_SERVICE_PORT_LDAP
Ignoring env var KANIDM_PORT_443_TCP_ADDR
Ignoring env var KANIDM_SERVICE_HOST
Ignoring env var KANIDM_SERVICE_PORT
Ignoring env var KANIDM_PORT_636_TCP_PROTO
Ignoring env var KANIDM_PORT
Ignoring env var KANIDM_PORT_636_TCP
Ignoring env var KANIDM_PORT_443_TCP
Ignoring env var KANIDM_PORT_443_TCP_PROTO
Ignoring env var KANIDM_PORT_636_TCP_PORT
Ignoring env var KANIDM_PORT_636_TCP_ADDR
Ignoring env var KANIDM_SERVICE_PORT_HTTPS
Ignoring env var KANIDM_PORT_443_TCP_PORT
Log filter: Info
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: This is running as uid == 0 (root) which may be a security risk.
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /data/server.toml may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /data/server.toml has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /data/server.toml owned by the current uid, which may allow file permission changes. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /data has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Running in server mode ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /data/ca.crt may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: permissions on /data/tls.key may not be secure. Should be readonly to running uid. This could be a security risk ...
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: /data/tls.key has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting kanidm with configuration: address: [::]:443, domain: auth.<DOMAIN>.com, ldap address: [::]:636, origin: https://auth.<DOMAIN>.com admin bind path: /data/kanidmd.sock, thread count: 20, dbpath: /data/kanidm.db, arcsize: AUTO, max request size: 262144b, trust X-Forwarded-For: false, with TLS: true, online_backup: disabled, integration mode: false, console output format: Text log_level: inforole: write replica, replication: disabled, otel_grpc_url: None
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     system_initialisation [ 40.2ms | 40.30% / 100.00% ]
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┝━ upgrade_reindex [ 187µs | 0.47% ]
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┝━ initialise_schema_core [ 11.5ms | 28.51% ]
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┝━ ｉ [info]: Before setting internal domain info | db_domain_version: 5
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┝━ initialise_domain_info [ 1.58ms | 3.94% ]
2cec52fa-2606-4710-be03-a92133db5ce6 WARN     │  ┕━ 🚧 [warn]: plugin_domain: NOT Applying domain version transform
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┝━ ｉ [info]: After setting internal domain info | db_domain_version: 5
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┝━ upgrade_reindex [ 7.22µs | 0.02% ]
2cec52fa-2606-4710-be03-a92133db5ce6 INFO     ┕━ qswt_commit [ 10.8ms | 26.77% ]
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting query server v1 worker ...
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Could not bind to LDAP server address [::]:636 -> Os { code: 98, kind: AddrInUse, message: "Address already in use" }
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to start server core!
Logging pipeline completed shutdown
0acfb4e9-3328-4e9d-af06-d54c6899a430 INFO     handle_purgetombstoneevent [ 6.76ms | 1.87% / 100.00% ]
0acfb4e9-3328-4e9d-af06-d54c6899a430 INFO     ┝━ ｉ [info]: Tombstone purge operation success | event_tag_id: 3
0acfb4e9-3328-4e9d-af06-d54c6899a430 INFO     ┕━ qswt_commit [ 6.63ms | 98.13% ]
c0f8c0ba-d7f2-4952-8a5e-ee4f99f16cd9 INFO     handle_purgerecycledevent [ 87.6µs | 100.00% ]
command terminated with exit code 1
```


Could be related to this:  https://github.com/kanidm/kanidm/pull/2686

**Comment by eenikad** [comment]
@numpythuckles are you still working on this issue? Ran into the same problem and would appreciate every possible hint.

**Comment by brimdor** [comment]
getting this issue as well, any progress on it?

**Comment by brimdor** [comment]
Temporarily created this yaml that I kubectl apply when post-install fails in order to manually create the kanidm.dex
I place this in the scripts folder and called it kanidm_fix.yaml then ran `kubectl apply -f scripts/kanidm_fix.yaml` assuming this is being run from the root homelab folder.

`apiVersion: batch/v1
kind: Job
metadata:
  name: secret-generator-kanidm-fix
  namespace: global-secrets
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: secret-generator
          image: lachlanevenson/k8s-kubectl:latest
          command:
            - sh
            - -c
          args:
            - |
              apk add --no-cache openssl
              CLIENT_ID=$(openssl rand -base64 32)
              CLIENT_SECRET=$(openssl rand -base64 64)
              kubectl create secret generic kanidm.dex \
                --from-literal=client_id="${CLIENT_ID}" \
                --from-literal=client_secret="${CLIENT_SECRET}" \
                -n global-secrets
      serviceAccount: secret-generator`

**Comment by lfleal** [comment]
Attempting to apply the above results in the following error:
`error: resource mapping not found for name: "secret-generator-kanidm-fix" namespace: "global-secrets" from "scripts/kanidm_fix.yaml": no matches for kind "Job" in version ""
ensure CRDs are installed first`

**Comment by brimdor** [comment]
That's strange. I built and ran this after post-install failed. Did you run it at that point in the process?

**Comment by lfleal** [comment]
First time I ran it:
`error: error validating "scripts/kanidm_fix.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false`
Running with --validate=false generated the error above. The file is missing `apiVersion`, does that exist in your file?

**Comment by brimdor** [comment]
Ah ok, it was there but it was next to the code block indicators so it cut it off. Its fixed.

**Comment by lfleal** [comment]
Adding `apiVersion: batch/v1` to the beginning of the yaml above fixes the error.

**Comment by brimdor** [comment]
Yep, as I stated, it is fixed.

**Comment by lfleal** [comment]
After getting the secrets added, I'm getting this now:
`error parse config file /tmp/dex.config.yaml-461377176: error unmarshaling JSON: parse connector config: invalid character '\n' in string literal
`

**Comment by khuedoan** [comment]
Thanks for reporting the issues everyone, I think the `./scripts/hacks` have grown big and messy, so I'll rewrite it to make it a bit more reliable

**Comment by khuedoan** [comment]
The following commits should fix the issue in the short term:

- https://github.com/khuedoan/homelab/commit/eb1381d38b7a315fb5ad5cb184d35ca35bd9e2a4
- https://github.com/khuedoan/homelab/commit/209a950ed08838d4950a6c39568530101bded77a

**Comment by khuedoan** [comment]
Closing as fixed, though I still need to rewrite the hacky script later
