### ISSUE TITLE
[Suggestion] Replace terraform with opentofu

### ISSUE THREAD

**Issue by Moortu** [khuedoan/homelab#156]
Terraform is going into the commercial business.
Opentofu is the opensource fork from terraform and should be a simple dropin replacement.

**Comment by kvendingoldo** [comment]
you can also you https://github.com/tofuutils/tenv to switch between different versions of terraform/tofu

**Comment by khuedoan** [comment]
Thanks, I'll replace Terraform with OpenTofu in the upcoming commits. I've been using it in some other projects as well (this will require some changes to `./external` and the prerequisites instructions though)

**Comment by khuedoan** [comment]
Switched to OpenTofu binary in https://github.com/khuedoan/homelab/commit/21fac43e57af3ee9fe3f9f62cf6d021c0bf41013 (we still use Terraform Cloud as the default backend option though)
