### ISSUE TITLE
Feature Proposal: Automatically update helm chart dependencies

### ISSUE THREAD

**Issue by koeberlue** [khuedoan/homelab#16]
Manually keeping all dependencies up to date can be a time consuming task which can easily be automated.

One possible solution for this is [renovatebot](https://docs.renovatebot.com) which periodically checks for new versions and can create a pull request for each update found.

It can easily be deployed on kubernetes via [helm](https://github.com/renovatebot/helm-charts) and works with [gitea](https://docs.renovatebot.com/getting-started/running/#gitea) out of the box.

**Comment by khuedoan** [comment]
Running Renovate manually and it's working, now I need to put it in a Job or Pipeline

https://github.com/khuedoan/homelab/commit/d6a8495767b79b519317153d006cec5ca7d04dd6

![image](https://user-images.githubusercontent.com/27996771/151420950-40aa21ba-33da-4039-85e1-6c6d6f385875.png)

**Comment by koeberlue** [comment]
Nice!

> now I need to put it in a Job or Pipeline

You could use the official helm chart for this:
https://github.com/renovatebot/helm-charts

It will deploy a kubernetes `CronJob` which just executes the bot at configurable intervals.

**Comment by khuedoan** [comment]
I tried that before but I [reverted it](https://github.com/khuedoan/homelab/commit/70c1b3f385426388519eefaa314fe3f19b0a8ce1), feels a bit weird. Anyway I'll play with it again to see which one is better.

**Comment by khuedoan** [comment]
This will need https://github.com/khuedoan/homelab/issues/20 https://github.com/khuedoan/homelab/issues/21 in the long term, but right now I'll just create the token and secret using the existing Python script.

**Comment by khuedoan** [comment]
Unfortunately, there is no way to generate a Gitea token with a specific value, so we must generate a token by hand and store it in Vault (it _can_ be automated, I've got it to work but it's kind of a mess):

https://github.com/khuedoan/homelab/blob/4e8de6307d9a3537c4fffc14b24e3191eecf0bcf/platform/renovate/templates/secret.yaml#L18-L19

![image](https://user-images.githubusercontent.com/27996771/159839774-4ba19d10-bb7d-44dc-8a2b-2507da7c4e3e.png)
