### ISSUE TITLE
Local run with docker not work (make tools)

### ISSUE THREAD

**Issue by GitHanter** [khuedoan/homelab#165]
```make tools``` get following error

```shell
error: unrecognised flag '--experimental-features'
Try 'nix --help' for more information.
make: *** [Makefile:30: tools] Error 1
```

**Comment by brimdor** [comment]
Refer to this fix - https://github.com/khuedoan/homelab/issues/139#issuecomment-1937418596

**Comment by khuedoan** [comment]
Thanks for reporting the issue, let's close this one and move to #172
