### ISSUE TITLE
PXE Server should not fail when running under DockerDesktop

### ISSUE THREAD

**Issue by kadaan** [khuedoan/homelab#175]
### Describe the bug

PXE Server startup failed when running under DockerDesktop due to [metal/roles/pxe_server/tasks/main.yml#L7C10-L7C39](https://github.com/khuedoan/homelab/blob/d98c1a164f3508d84202fdd0fdbcd345dafa6abd/metal/roles/pxe_server/tasks/main.yml#L7C10-L7C39.)  However, DockerDesktop support host networking starting from version 4.34: https://docs.docker.com/engine/network/drivers/host/#docker-desktop

**Comment by khuedoan** [comment]
Unfortunately it won't work with PXE, from the linked doc:

> The host network feature of Docker Desktop works on layer 4. This means that unlike with Docker on Linux, network protocols that operate below TCP or UDP are not supported.
