### ISSUE TITLE
Domain replacement not changing URL in .tekton/pipelines/pipeline.yaml

### ISSUE THREAD

**Issue by dexter136** [khuedoan/homelab#18]
https://github.com/khuedoan/homelab/blob/7e21741bc1362206e392a663b9e5b722f874368e/.tekton/pipelines/pipeline.yaml#L42

I am prepping to test your project out on my own setup and noticed that the pipeline.yaml file references registry.khuedoan.com, even after running the domain replacement scripts.

I switched the line manually for my config, but I am not well versed in docker so I am not 100% sure that it is incorrect in the first place.

**Comment by locmai** [comment]
The domain replacement script is going through this list [apps platform system scripts] of the folder, `.tekton` is not one for them so. Creating a PR for this one.

Ideally you would update the script like this:
```
#!/bin/sh

CURRENT_DOMAIN="khuedoan.com"

git grep "${CURRENT_DOMAIN}" -- apps platform system scripts .tekton | cut -d ':' -f1 | uniq | while read p; do
  sed -i "s/${CURRENT_DOMAIN}/${1}/g" $p
done
```

**Comment by dexter136** [comment]
Yeah, I was testing that and it was not working, then I realized I was not in the scripts folder. Thanks for the help!

**Comment by khuedoan** [comment]
Merged, thanks @locmai!
