### ISSUE TITLE
Gitea SSH clone doesn't work with Cloudflare Tunnel using the same subdomain

### ISSUE THREAD

**Issue by khuedoan** [khuedoan/homelab#22]
The following command works in LAN but not from the internet:

`git clone git@git.MYDOMAIN.com:ops/homelab.git`

- Cloudflare Tunnel config: https://github.com/khuedoan/homelab/blob/d18bb02cbf02a6a5ed9ae25ae6885e2b09696e1d/system/cloudflared/values.yaml#L6-L13
- NGINX TCP config: https://github.com/khuedoan/homelab/blob/d18bb02cbf02a6a5ed9ae25ae6885e2b09696e1d/system/ingress-nginx/values.yaml#L9-L10

**Comment by xxxcrow** [comment]
It seems for ssh and any other port except web browser stuff you need to have same cloudflared installed on your client machine ☝️
Also, i read some people manage it with warp clients, but it seems like a complicated and boring story 😅
Also, as i understood there's probably a way with cloudflare spectre, which is avaliable for cloudflare pro plan
But the easiest is to install cloudflared on your client 😁

**Comment by khuedoan** [comment]
Thanks, even in [Cloudflare's example](https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab#connecting-to-cloudflare), they're using a separate domain :disappointed:

Marking as won't fix for now (I'm using Gitea via LAN).

**Comment by xxxcrow** [comment]
In their example they use cloudflared on client too
Also, worth mentioning some of their documentation sometimes is outdated, and some is very confusing
And, though cloudflared is opensource, but the devs seem to get paid from cloudflare, so they have no intention to add good free features 🥲

**Comment by xxxcrow** [comment]
https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab#configuring-ssh
Like that
