### ISSUE TITLE
Seafile is non-functional. Updating to newest release resolves issue.

### ISSUE THREAD

**Issue by dexter136** [khuedoan/homelab#26]
After setting up your project on my own system I found that Seafile was throwing an HTTP error when I navigated to the URL. I believe it was 500, but I did not record it.

Pod logs showed that the Seafile pod was not able to authenticate to the mariadb instance.

Updating the helm chart version, and adding SEAFILE_SERVER_HOSTNAME to the values.yaml resolved this.

The changes I made are in [this PR](https://github.com/dexter136/homelab/commit/ea2ca6f1b02a1d39c268ce4f911c7970450b8fcd) to my fork of your repository.

**Comment by khuedoan** [comment]
Thank you! Do you want to make a PR to take credit for the commit? (If not, I can add you as a co-author when I commit)

Because I'm still working on `./system` and `./platform`, some of the applications in './apps' may not work.

**Comment by dexter136** [comment]
I am not able to make a PR to this repository.

**Comment by khuedoan** [comment]
In that case let me cherry-pick your commit then, thanks again!

**Comment by dexter136** [comment]
Thank you for the great project!

**Comment by khuedoan** [comment]
Fixed in https://github.com/khuedoan/homelab/commit/31516447db178d5c75bdd18fcf1d3d1e546e8548, I've added you as a co-author
