### ISSUE TITLE
Paperless is not functional

### ISSUE THREAD

**Issue by khuedoan** [khuedoan/homelab#28]
This is a known issue, I just didn't have a chance to look at it yet.

**Comment by Jsakkos** [comment]
I've got a functional Paperless-ngx config here: https://github.com/Jsakkos/k3s-homelab/tree/master/apps/paperless

**Comment by khuedoan** [comment]
This is fixed in https://github.com/khuedoan/homelab/commit/11e407e880762f105f30a493680b5763736f3186, thanks everyone!
