### ISSUE TITLE
Rewrite configure script in pure Python

### ISSUE THREAD

**Issue by khuedoan** [khuedoan/homelab#30]
Right now it's just a thin Python wrapper for a bunch of shell scripts, which is very ugly. New version will need:

- Pure Python
- Input validation (see https://github.com/khuedoan/homelab/issues/29#issuecomment-1022471189 for a possible case)
- Preferably idempotent

Additional features:

- [x] Timezone

**Comment by locmai** [comment]
All of these scripts you mean https://github.com/khuedoan/homelab/tree/master/scripts?

**Comment by khuedoan** [comment]
No just the scripts invoked by `configure.py`

**Comment by khuedoan** [comment]
Not very clean yet, but [368535f](https://github.com/khuedoan/homelab/commit/368535f41c6a815a01c0563452b3e1bf14571328) is pure Python now.
