### ISSUE TITLE
SSH tunnel as alternative to Argo

### ISSUE THREAD

**Issue by xxxcrow** [khuedoan/homelab#31]
Hello, awesome project, now i know what thing i want to have in my life 😊

I tried to ask you this on Reddit, but therecs too many people and you probably didn't see 😅

Is it possible to run something like an email server, or minecraft, etc? I didn't manage to make it with argo tunnels

So i have a pruposal to add some ssh tunneling agent on the same layes as argo tunnels, so people that need to selfhost email or anything like that can have it
Also, just for users that don't like cloudflare, and free argo tunnel restrictions

(P.S. a side question, about jenkins, does this project have an alternative to jenkins? 😄 which one is it, and can i vuild aosp on it?)

Thank you, awesome project ✌️

**Comment by xxxcrow** [comment]
And also, is ssh for gitea working? 🤔

**Comment by khuedoan** [comment]
Cloudflare Tunnel doesn't work with mail server, but it does work for most HTTP and TCP connections. Seems like [they're adding support for UDP](https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns). I don't host any game server yet so please try and let me know :wink:

I won't add anything that I don't personally use, but I can update the docs for some alternatives. You can implement your own version of Cloudflare Tunnel using a small VPS with Wireguard and HAproxy.

The CI platform is mentioned in the README, which is Tekton.

SSH for Gitea works in LAN but not via Cloudflare Tunnel, that's a know issue, see #22

**Comment by khuedoan** [comment]
Documentation updated in https://github.com/khuedoan/homelab/commit/b6aa20a0ee2cc19e42ef496e4027f17de669ba06
