### ISSUE TITLE
"Bring your own cluster" mode

### ISSUE THREAD

**Issue by Zorlin** [khuedoan/homelab#32]
Hey there!

I've got a Kubernetes cluster I've deployed myself, and am not hugely keen on PXE booting. It would be super awesome if there was a way to use this project while skipping past the PXE boot and provisioning stuff.

In fact, there basically is already a way! Copy your kube configs into place, then...

make -C bootstrap instead of make, and bam... you've got a khuedoan homelab, kind of.

Maybe you could have a target like "make existing-cluster" or something which officially supports this deployment method?

**Comment by khuedoan** [comment]
You can already run `make bootstrap` (without `-C`), if you want to change the `KUBECONIFG` path you can change it here:

https://github.com/khuedoan/homelab/blob/3ffaf84a30042f54a48de52b146a1b0f4947617f/bootstrap/Makefile#L4

Since you're forking this repository to add your own modifications anyway this should be easy.

**Comment by Zorlin** [comment]
I suppose what I'm getting at is roughly this:

There's currently an unofficial way to bootstrap without creating a new cluster, please don't take it away! :) And maybe even make it officially supported.

**Comment by khuedoan** [comment]
Yeah I won't take it away, I specifically designed this homelab to make it easy to customize :)

**Comment by khuedoan** [comment]
To add to that you can remove the metal layer completely and add your own Terraform, scripts or things like that to create your current cluster.

**Comment by Zorlin** [comment]
Awesome! I'm very much following this project and seeing where it goes. It goes along way towards my dream of a "company in a box"...

**Comment by khuedoan** [comment]
That's [on the roadmap :wink](https://homelab.khuedoan.com/roadmap.html#stable-requirements): 

![image](https://user-images.githubusercontent.com/27996771/151423059-ec297489-6e00-4ae2-8f15-c17e78a9039e.png)
