### ISSUE TITLE
Try it on a VM link 404's

### ISSUE THREAD

**Issue by tielur** [khuedoan/homelab#33]
The link in the readme to Try it on a VM is returning an HTTP 404
https://homelab.khuedoan.com/try_on_a_vm

**Comment by locmai** [comment]
https://homelab.khuedoan.com/try_on_a_vm.html

**Comment by locmai** [comment]
Look like something is wrong with the new doc build that require the .html tail.

**Comment by khuedoan** [comment]
You're right something is wrong with the new docs build, I recently migrated the docs from GitHub Pages to my other cluster at [khuedoan/horus](https://github.com/khuedoan/horus). I've made a hot fix and will check why the behavior changed later.

**Comment by khuedoan** [comment]
The prior behavior (without the `.html` suffix) turns out to be from GitHub Pages, not mdbook, hence changing the URL suffices (https://github.com/khuedoan/homelab/commit/be166fdbede9d3d0d9e6d9d0bd9c54001e42679b).

**Comment by tielur** [comment]
Ahh ok I assume deployment is built differently then because that doesn't seem to have an issue without the html suffix https://homelab.khuedoan.com/deployment

**Comment by khuedoan** [comment]
I think it's because `/deployment` is [a directory](https://github.com/khuedoan/homelab/tree/master/docs/src/deployment), and it defaults to https://homelab.khuedoan.com/deployment/index.html (with the `index.html` suffix)

**Comment by tielur** [comment]
> I think it's because `/deployment` is [a directory](https://github.com/khuedoan/homelab/tree/master/docs/src/deployment), and it defaults to https://homelab.khuedoan.com/deployment/index.html (with the `index.html` suffix)

Oh that makes complete sense! Thanks for replying
