### ISSUE TITLE
Vagrant Error | The following settings shouldn't exist: disk

### ISSUE THREAD

**Issue by r00t9** [khuedoan/homelab#34]
I am trying to create the VMs with the command 

`VAGRANT_CWD=./metal vagrant up`

but I get this error. Any ideas ? i can remove the reboot but disk? :/ 

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: disk

shell provisioner:
* The following settings shouldn't exist: reboot

```

**Comment by locmai** [comment]
Probably update your vagrant version would help
Installed Version: 2.2.19
Latest Version: 2.2.19

**Comment by r00t9** [comment]
yes sorry, i forget to check the version :/ thanks and sorry :)
