### ISSUE TITLE
Loki values file is invalid

### ISSUE THREAD

**Issue by dexter136** [khuedoan/homelab#39]
https://github.com/khuedoan/homelab/blob/9b51109cae23cd3bf823ee93288a4b45e4a87683/system/loki/values.yaml#L1-L3

This needs to be under the heading `loki-stack:`. Currently this does not enable the service monitor, as the values are not read.

**Comment by khuedoan** [comment]
Thanks! Fixed in 4ac77de79e126413e2be71c8b9faaa68542a077a.

**Comment by dexter136** [comment]
I did not state that properly. The configuration should be:
loki-stack:
 loki:
  serviceMonitor:
   enabled: true

**Comment by khuedoan** [comment]
I need some coffee lol. Fixed in 6fd1ba1
