### ISSUE TITLE
dev0 is unreachable

### ISSUE THREAD

**Issue by chickencoding123** [khuedoan/homelab#42]
Been trying to run my fork of this amazing project, but so far had no luck. After fixing a few bumps with docker, I'm finally stuck at running the `dev` inventory via `make dev`. I assume we run `make dev` after tools container becomes interactive (by running `make tools`). Then:

Which interface should be used to configure the `metal/inventories/dev.yaml` file? I tried every single interface I could find on my host machine after running `ipconfig` outside tools container, but they all failed with connection timeout or connection refused on port 22. Next tried to add the private ssh-key for ansible (~/.ssh/id_ed25519) inside of the tools container which did not help.

**Error**
```
ansible-playbook \
	--inventory inventories/dev.yml \
	cluster.yml

PLAY [Create Kubernetes cluster] **************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************
fatal: [dev0]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: ssh: connect to host <an inet from ipconfig result> port 22: Connection timed out

PLAY RECAP ************************************************************************************************************************
dev0                       : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by khuedoan** [comment]
Are you using the included Vagrant VM and the `dev.yml` inventory?

**Comment by chickencoding123** [comment]
Yes i'm using `dev.yml`, but have no idea what IP to set it to. I don't have a server, just my own laptop so is this something we can do with this repo? If so, then how to get the SSH working between VM and the host?

**Comment by locmai** [comment]
The document is a quite good place to start with https://homelab.khuedoan.com/try_on_a_vm.html

**Comment by chickencoding123** [comment]
I did read the docs and followed it step by step. However it did not mention that the `ansible_host` of `dev0` node under the `metal/inventory/dev.yaml` is in fact IP address of the Vagrant box. Also we have to have the Vagrant box running via `VAGRANT_CWD=./metal vagrant up` before running the `make dev` inside the tools container.
