### ISSUE TITLE
Can't bind to port 80 because it's already in use

### ISSUE THREAD

**Issue by dotdiego** [khuedoan/homelab#43]
I've just launched the script with my own configuration.

I didn't changed anything but i'm getting an error on the pxe-logs

```
^[[19dhttp_1  | nginx: [emerg] bind() to [::]:80 failed (98: Address in use)
^[[20dhttp_1  | 2022/02/13 21:07:24 [notice] 1#1: try again to bind() after 500ms
^[[21dhttp_1  | 2022/02/13 21:07:24 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address in use)
```

Yet i don't have any nginx running on and no port listening to 80 active other than the one set when running make.

Do you have any idea where can be the issue ?

Wakeonlan works well but then the pxe install doesn't work.

Running the make

This is what's showing on the ports when i'm running the make command

![capture_httpbug](https://user-images.githubusercontent.com/57672481/153906532-32a05bc3-7e19-4a16-bf01-f458f37703a3.PNG)

**Comment by khuedoan** [comment]
Unfortunately I don't know what's in your system (running processes, services, containers...), so you'll need to find it yourself and kill it first.

**Comment by dotdiego** [comment]
I killed everything, before starting the script.
So when I start the script there's nothing listening on port 80. I'll continue looking seems i have some errors on the dhcpd.conf file created by ansible too

**Comment by dotdiego** [comment]
Ok, so i'm getting there slowly. The issue here was some container for http/dhcp was not properly removed.
But I still can't get the DHCP to work.

**Comment by dotdiego** [comment]
At the end of the day it was all configs errors.

Firsts a container badly removed.
Second a dhcp that was not on the right scope.

Thanks for the answer.
