### ISSUE TITLE
how do you manage Data in case of cluster rebuild

### ISSUE THREAD

**Issue by vincentDcmps** [khuedoan/homelab#46]
HI I'am new in kubernetes, I ask myself some question on restauration/secret management if you could help me
- in case of rebuild cluster how to restore data on database or reuse persistant volume?
- if I uninstall and install helm release this will generate new secret not according with database current password how do you manage this?
- I can maybe create some custom secret resource to avoid this but what is best method to create this one?

**Comment by khuedoan** [comment]
![image](https://user-images.githubusercontent.com/27996771/154827223-9b00d7dc-6007-4024-9202-f1754bba8024.png)

Joke aside:

1. WIP https://github.com/khuedoan/homelab/issues/23
2. Does that matters if the password (for example ArgoCD admin password) changed?
3. WIP https://github.com/khuedoan/homelab/issues/21

**Comment by vincentDcmps** [comment]
For the second question I Spoke of sql password. But I think if I create a custom secret this fix this issue

**Comment by khuedoan** [comment]
Yes, `auth.existingSecret` should work (assuming you're using Bitnami's MySQL chart).

**Comment by vincentDcmps** [comment]
Yes I see that but I come back on the third question how to store secret outside of kubernetes 😂

**Comment by khuedoan** [comment]
That's in the third answer, still WIP lol

**Comment by vincentDcmps** [comment]
In your GitHub I don't see secret use, if I understand you use vault? But you never call any secret In your configuration

**Comment by khuedoan** [comment]
Yep there's nothing there yet, because it's still in the work :wink:

**Comment by locmai** [comment]
All of your concerns are fall into one of the following categories:
- Cluster/database backup and restore
- Secret management #21 
- Data handling with operations like re-install

As @khuedoan stated that there are some on-going efforts around those stuffs, we just don't have them fully functional at the current state of the project.

The project state that we have right now is: We have a minimal set of secrets that we need for the provisioning and we use them to spin up the whole cluster.

That's it.

For each of those items, we would need to: evaluate the solution, work on it, test it, document it. So I suggest if you need a feature, breaking them down into smaller issue on this GitHub repository, label them as feature request and we could take a look, discuss on the implementation details, keep track on the progress.

**Comment by vincentDcmps** [comment]
No problem, I'm just trying to understand how the project works. I just wanted to be sure I understood it correctly.

**Comment by khuedoan** [comment]
Closing as the question is answered.
