### ISSUE TITLE
Python configure.py throwing if nothing to replace

### ISSUE THREAD

**Issue by dotdiego** [khuedoan/homelab#47]
There seems to be an error thrown by Python when running `find_and_replace`  function: 

`subprocess.CalledProcessError: Command '['git', 'grep', '--files-with-matches', 'https://github.com/khuedoan/homelab', '--', 'bootstrap', 'platform']' returned non-zero exit status 1.`

```python
def find_and_replace(pattern: str, replacement: str, paths: list[str]) -> None:
    files_with_matches = subprocess.run(
        ["git", "grep", "--files-with-matches", pattern, "--"] + paths,
        capture_output=True,
        text=True,
        check=**True**
    ).stdout.splitlines()
```

The bug seems to happen when no matches are found. (I replayed the configure.py just to change the domain, github repo was already the same)
I changed the check value to **False** to make it work again.

**Comment by khuedoan** [comment]
Thanks! Fixed in [`03ee03f`](https://github.com/khuedoan/homelab/commit/03ee03ffee49b69a300506e8578248bd30c957d5)
