### ISSUE TITLE
configure.py error "TypeError: 'type' object is not subscriptable"

### ISSUE THREAD

**Issue by bpersino** [khuedoan/homelab#53]
python3 ./configure.py 

Text editor (vim): 
Enter your domain (khuedoan.com): 
Enter seed repo (https://github.com/khuedoan/homelab): 
Enter time zone (Asia/Ho_Chi_Minh): 
Enter your Terraform Workspace, skip if you don't want to use external resources yet (khuedoan): 
Traceback (most recent call last):
  File "./configure.py", line 27, in <module>
    def find_and_replace(pattern: str, replacement: str, paths: list[str]) -> None:
TypeError: 'type' object is not subscriptable

**Comment by khuedoan** [comment]
Thanks for opening an issue but this is not a good bug report. You'll need to provide more information than just some unformatted code:

- Your environment (OS, Python version...)
- What is your input
- Format your code block with ` ``` `
- etc.

**Comment by bpersino** [comment]
I cloned the github repo, edited the ./configure.py to change your default values to mine and then attempted to run the ./configure.py script. I tried using both python v2 and v3. 

Lines that I changed in ./configure.py.  Everything else is default.
```
default_editor = os.getenv('EDITOR') or "vim"
default_seed_repo = "https://github.com/bpersino/homelab"
```

```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
```
$ python2 --version
Python 2.7.18
```
```
$ python3 --version
Python 3.8.10
```
```
$ python2 ./configure.py 
  File "./configure.py", line 20
    editor = str(input(f"Text editor ({default_editor}): ") or default_editor)
                                                         ^
SyntaxError: invalid syntax
```
```
$ python3 ./configure.py 
Text editor (vim): 
Enter your domain (bpersino.com): 
Enter seed repo (https://github.com/bpersino/homelab): 
Enter time zone (Asia/Ho_Chi_Minh): 
Enter your Terraform Workspace, skip if you don't want to use external resources yet (): 
Traceback (most recent call last):
  File "./configure.py", line 27, in <module>
    def find_and_replace(pattern: str, replacement: str, paths: list[str]) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by khuedoan** [comment]
You don't need to change the configuration script, just run it and type the answer. The answers in `()` are the default values.

**Comment by bpersino** [comment]
I get the same error even after manually tying in my answers.

```
$ python3 ./configure.py 
Text editor (vim): vim
Enter your domain (khuedoan.com): bpersino.com
Enter seed repo (https://github.com/khuedoan/homelab): https://github.com/bpersino/homelab
Enter time zone (Asia/Ho_Chi_Minh): America/Chicago
Enter your Terraform Workspace, skip if you don't want to use external resources yet (khuedoan): 
Traceback (most recent call last):
  File "./configure.py", line 27, in <module>
    def find_and_replace(pattern: str, replacement: str, paths: list[str]) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by bpersino** [comment]
```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
```
$ python2 --version
Python 2.7.18
```
```
$ python3 --version
Python 3.8.10
```

**Comment by dotdiego** [comment]
I think i had the same issue back in my first tries. 
I finally ran it using python3.10. 

You shouldn't change the defaults in the configure.py right at the beginning. Because those values are used to replace defaults in lots of files in the repository.

**Comment by dotdiego** [comment]
@khuedoan one improvement could be to replace the defaults in the configure.py or in a side configuration file after it ran. This way we wouldn't lose the replace functionality if we need to rerun the configure script

**Comment by bpersino** [comment]
Thank you dotdiego. Python 3.10 fixed the issue.

```
$ python3.10 ./configure.py
```

**Comment by khuedoan** [comment]
Thanks, I've added a check in https://github.com/khuedoan/homelab/commit/e27ecd898ecb567ce29bea8bf8fadcd613702c1a

@dotdiego the forked repositories need to replace my config when they fetch from my upstream, if we replace that they need to do that manually.
