### ISSUE TITLE
Node Storage Size Question

### ISSUE THREAD

**Issue by cturner-confluent** [khuedoan/homelab#54]
I have just started to read through your docs and it's great so first of thanks for all the great work putting this together for everyone to use. I was wondering if the 128gb disk size requirement for the nodes is a true hard  requirement or if the node could function with a smaller disk size? I don't have a specific target size but something smaller than 128gb would better fit my use case.

**Comment by khuedoan** [comment]
It's not a hard requirement, but it may change in the future. Below is my current disk usage (4 nodes with 2 replicas):

```
khuedoan@all (4)[f:5]$ df -H /
metal1 | CHANGED | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       125G   23G   96G  20% /
metal0 | CHANGED | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       125G   26G   94G  22% /
metal2 | CHANGED | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       125G   22G   98G  19% /
metal3 | CHANGED | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       125G   25G   95G  21% /
```

You can [reduce the replica count](https://github.com/khuedoan/homelab/blob/e27ecd898ecb567ce29bea8bf8fadcd613702c1a/system/longhorn-system/values.yaml#L6) but you will lose data when a node goes down.

**Comment by curtis-turner** [comment]
Gotcha thanks @khuedoan for the quick reply. So it sounds like a good number of nodes is at least 4, is there a recommended split for the master and worker nodes, i.e. 2 masters and 2 workers when doing 4 nodes total that is?

**Comment by khuedoan** [comment]
A good number of nodes is `>= 3` (as mentioned in [hardware requirements](https://homelab.khuedoan.com/deployment/prerequisites.html#servers)).

You'll need at least 3 masters for HA (the masters also run workload, so they actually are also workers). I have 3 masters and 1 worker:

- metal0: master + worker
- metal1: maser + worker
- metal2: master + worker
- metal3: worker

**Comment by cturner-confluent** [comment]
Perfect thanks for this info I believe we can close this is issue and I'll label it as a question. Thanks again for the quick response.
