### ISSUE TITLE
Unable to access resources behind cloudflared. 

### ISSUE THREAD

**Issue by cheers1999** [khuedoan/homelab#61]
### Describe the bug

- [x] I have read the document

### To reproduce

1. Follow the instructions on the repo to deploy the lab and run the external layer. 

### Expected behavior

Access the lab via my domain. 

### Additional context

 I can get to the the hajimari page and see resources found on the apps folder.   Argocd & git are not working. I get a cloudflared error( 1033)

**Comment by khuedoan** [comment]
Is it accessible via LAN? Most services are only accessible via LAN by default, you must [explicitly allow internet access](https://homelab.khuedoan.com/tutorials/expose-services-to-the-internet.html).

Could you please provide the following additional information:

- Are you accessing Hajimari via LAN or internet?
- Your homelab repository
- Cloudflare tunnel logs (available from the `cloudflared` namespace) 
- Ingress addresses (`./scripts/get-dns-config`)
- DNS config on Cloudflare dashboard (this should be updated automatically, just double checking)

**Comment by cheers1999** [comment]
Thanks for the quick reply.  Yes, I enabled by following those instructions. 

1. Accessing it via LAN.
2. gitlab.com/rijndael128/homelab
3. Looks like terraform apply failed , and the cloudflare namespace was not created. 
 - `
│ Error: Get "http://localhost/api/v1/namespaces/cloudflared/secrets/cloudflared-credentials": dial tcp 127.0.0.1:80: connect: connection refused
│
│   with module.cloudflare.kubernetes_secret.cloudflared_credentials,
│   on modules/cloudflare/main.tf line 43, in resource "kubernetes_secret" "cloudflared_credentials":
│   43: resource "kubernetes_secret" "cloudflared_credentials" {
│
╵
╷
│ Error: Get "http://localhost/api/v1/namespaces/external-dns/secrets/cloudflare-api-token": dial tcp 127.0.0.1:80: connect: connection refused
│
│   with module.cloudflare.kubernetes_secret.external_dns_token,
│   on modules/cloudflare/main.tf line 79, in resource "kubernetes_secret" "external_dns_token":
│   79: resource "kubernetes_secret" "external_dns_token" {
│
╵
╷
│ Error: Get "http://localhost/api/v1/namespaces/cert-manager/secrets/cloudflare-api-token": dial tcp 127.0.0.1:80: connect: connection refused
│
│   with module.cloudflare.kubernetes_secret.cert_manager_token,
│   on modules/cloudflare/main.tf line 110, in resource "kubernetes_secret" "cert_manager_token":
│  110: resource "kubernetes_secret" "cert_manager_token" {
`
4. `10.10.69.224   argocd.weyland.io
10.10.69.224   dex.weyland.io
10.10.69.224   git.weyland.io
10.10.69.224   home.weyland.io
10.10.69.224   jellyfin.weyland.io
10.10.69.224   chat.weyland.io
10.10.69.224   matrix.weyland.io
10.10.69.224   grafana.weyland.io
10.10.69.224   paperless.weyland.io
10.10.69.224   seafile.weyland.io
10.10.69.224   tekton.weyland.io
10.10.69.224   registry.weyland.io
10.10.69.224   vault.weyland.io`

5. 
![image](https://user-images.githubusercontent.com/105739889/168946180-af2cb215-c407-4086-86e1-9d0fe56bdb02.png)

Also, the tunnel was created but it shows as inactive on the cloudflare dashboard.

**Comment by khuedoan** [comment]
Are you building the external layer using `cd external && make` or running `make external`/`make all` from the root directory of the project?

I think it's due to the change in this commit https://github.com/khuedoan/homelab/commit/dc7d1256a00e545c848e51537cc297b370ae10e7, can you try again by running `make external` from the root directory of the project (I'll need to update the documentation).

Btw please keep the copy right notice or add an acknowledgement to your repo in case you forgot 😉

**Comment by cheers1999** [comment]
Thanks!

I've been running external from the external folder.

I've been using your repo to learn, sorry I missed the copyright. I deleted
quite a few things in one of those moments of frustration, and I must have
deleted that as well. I'll correct that quickly.

I appreciate you taking the time to help, I'll follow your instructions and
report back.

**Comment by cheers1999** [comment]
Alright, looks like that was it.  More user error than a bug.  Dex is having trouble with `
secret "dex-secrets" not found `, but I can go ahead and troubleshoot that. Thanks for the help!!
