### ISSUE TITLE
Kickstart script curl request fails due to case-sensitive MAC address

### ISSUE THREAD

**Issue by gitfrederic** [khuedoan/homelab#65]
### Describe the bug

My PXE controller is a Linux (Arch Linux) box and the kickstart script download from it is failing early in the setup, e.g.
```
curl: (22) The requested URL returned error: 404 Not Found
Warning: anaconda: failed to fetch kickstart from http://192.168.x.x/init-config/84:xx:xx:xx:a0:dc.ks
```
NOTE: The 'x' and 'xx' values are for privacy (i.e. not actual values).

- [x] I have read the document

### To reproduce

I'm suspecting this may happen when the controller is using a filesystem that is case-sensitive.

### Expected behavior

That the .ks script would be downloaded from the controller without any intervention.

### Additional context

As a workaround, I simply copied the generated .ks script to match the case used by curl, e.g.
```
$ cp ./metal/roles/pxe_server/files/data/init-config/84:xx:xx:xx:A8:DC.ks ./metal/roles/pxe_server/files/data/init-config/84:xx:xx:xx:a8:dc.ks
```

**Comment by khuedoan** [comment]
Please see https://homelab.khuedoan.com/deployment/configuration.html#run-the-configure-script

> MAC address: **the lowercase**, colon separated MAC address of the above network interface
