### ISSUE TITLE
Localhost Not a Valid IP Address During "pxe_server" Task

### ISSUE THREAD

**Issue by savager** [khuedoan/homelab#7]
Following the instructions in the documentation went smoothly. Updated all ansible hosts. Launched homelab-tools container on a debian machine (supports --host networking). But when running make -c metal I get the following error. I have tried adding "-c local" to the ansible-playbook boot.yml to no avail. Thanks for any insights.

![image](https://user-images.githubusercontent.com/1455337/147798187-a266e4b4-cdaa-4677-b4e6-ea55847a7f27.png)

**Comment by savager** [comment]
modified the tools docker image and seems to fix the problem.

RUN pip install netaddr docker-compose

**Comment by khuedoan** [comment]
Strange, we already install netaddr in the tools container https://github.com/khuedoan/homelab/blob/master/tools/Dockerfile#L28

**Comment by savager** [comment]
I stand corrected. I thought it was that addition, but it was actually my removal of this portion of the dhcp template:

```{{ ansible_default_ipv4.broadcast | ansible.netcommon.ipmath(-1) }}```

**Comment by khuedoan** [comment]
Ah, the `ansible_default_ipv4` variable is not very consistent, it may use the incorrect interface. I may switch to other method to find the network information in the feature.

**Comment by savager** [comment]
Sounds good. I don't think I need the DHCP server at all currently so I will close this issue.
