### ISSUE TITLE
Proposal: Add option to use DNSMasq

### ISSUE THREAD

**Issue by Bourne-ID** [khuedoan/homelab#70]
Good day. 

### Issue statement
The use of dhcpd is great for air-gap solutions where a new DHCP is required. However for some home networks which does not have the VLAN capability or for users who would like to use common router DHCP services, the use of DHCPD will cause duplicate DHCP servers and will result in potential network disruption, or will limit the ability to auto-provision the Metal stage of this project. 

### Proposed Solution: DHCP Proxy
Use DHCP Proxy services to add PXE features such as Next Server into this project. This allows for users to use the existing DHCP servers which may be locked down or incapable of using Next Server/PXE settings on their network to be able to auto-provision hardware through PXE (with certain common configurations, like static IP allocation or reduction in DHCP request ranges on the DHCP server) 

### Proposed Application: DNSMasq
DNSMasq in Proxy mode interoperates with existing DHCP servers over IPv4 to add features such as next-server, TFTP, etc. where such hardware is either locked or unconfigurable for such services. This would be an opt-in change, configurable through the pxe_server defaults file.

### Proposed Target Audience
Users who either do not want to create their own VLAN or lack the hardware to configure such services. Users who want to use common router services for DHCP and have router access to configure static IP and/or DHCP allocation ranges. 

### Additional Risks with Proposed Change
* Additional Surface Area for Break-Out Attacks: Originally this project is locked to its own DHCP/VLAN, so any break-outs should be contained accordingly. Using common home networks increases the surface area of break-out attacks if the deployment is compromised. 
  * Mitigation: Enrolment into this change is opt in only. 
### Proposed Next Steps
1) Trial/Adopt/Halt - A discussion with all or a decision by the project maintainers to identify if this change should exist in this project or live on a fork. 
2) Documentation (This is in flight in any situation).

**Comment by Bourne-ID** [comment]
PR https://github.com/khuedoan/homelab/pull/69/ Relates to this change

**Comment by khuedoan** [comment]
Thanks for a very detailed proposal, I planned to move to `dnsmasq` for the DNS proxy feature but got side tracked (prior attempt https://github.com/khuedoan/homelab/commit/c26db4d11ad14834247d0d6a66d6793d75d27c0d), so this is a welcome change :tada:

I prefer we replace `dhcpd` and `tftpd` with `dnsmasq` instead of adding a new option because:

- We can still have the previous behavior with `dnsmasq`
- Backward compatibility is not a problem because we're still in the Alpha stage
- Reduce the complexity

**Comment by Bourne-ID** [comment]
Sounds good - I'll make the changes on my fork, test and comment again when ready for review :)

**Comment by Bourne-ID** [comment]
PR #69 ready for candid review.

**Comment by khuedoan** [comment]
https://github.com/khuedoan/homelab/pull/69 is merged.
