### ISSUE TITLE
Paramiko Error Reading SSH Protocol Banner

### ISSUE THREAD

**Issue by savager** [khuedoan/homelab#8]
Nodes don't seem to connect. I am probably doing something wrong as I am still learning Ansible. 

Wondering does this mean the PXE boot to rocky has completed? 

In the file ./metal/group_vars/all.yml do I need to generate the ed25519 ssh key? 

![image](https://user-images.githubusercontent.com/1455337/147805090-20a37897-eba1-4127-b26a-382cd9060923.png)

Thanks for any info!

**Comment by khuedoan** [comment]
The SSH key should be generated automatically if it doesn't exists:
https://github.com/khuedoan/homelab/blob/fc2987ee42cc77354545a52a4174d5511d59ec2e/metal/Makefile#L8

However, debugging PXE boot is a bit tricky (a monitor is highly recommended), have you tried the following https://homelab.khuedoan.com/troubleshooting.html?

**Comment by locmai** [comment]
I recalled to have this one when my servers auto-booted into the **pre-installed Ubuntu** that I had. What I did was plugged the monitor in and manually pick the correct boot option. After that, it's all okay.

**Comment by savager** [comment]
Thanks! I’ll give that a read.

**Comment by savager** [comment]
This actually makes perfect sense because I also have a Ubuntu pre-installed. I will hookup a monitor and look.

**Comment by savager** [comment]
I can close this as my nodes were not in the PXE ready state. Sorry for the false issue.
