### ISSUE TITLE
use /dev/disk/by-uuid/ instead of /dev/sd*

### ISSUE THREAD

**Issue by airtonix** [khuedoan/homelab#81]
`/dev/sd*` is a positional reference of the drives, the order is not garunteed. 

instead use `/dev/disk/by-uuid/*`

**Comment by khuedoan** [comment]
I purposefully used `/dev/sda` instead of UUID to make new user onboarding easier, but in theory you can just update the inventory to use `disk/by-uuid/foo` instead.
