### ISSUE TITLE
Installing docker-compose python sdk should not be necessary anymore

### ISSUE THREAD

**Issue by dotdiego** [khuedoan/homelab#83]
Version 3.0.0 of _community.docker_ ansible collection has removed all connections to the Python SDK.  

You can safely remove the following instruction from the tools Dockerfile.

`RUN pip install docker-compose` 

By the way thanks for this amazing repo. I'm using it at a base to create my own homelab deployment framework with Docker Swarm. Kubernetes learning curve is a bit too steep for my usage right now.

**Comment by dotdiego** [comment]
Seems it's stale, I didn't check the latest evolution of your repository.

**Comment by khuedoan** [comment]
Thanks, I'm still using the docker-compose v1 (Python), just with a different installation method (via Nix instead of pip):

https://github.com/khuedoan/homelab/blob/ea1d597b33c248b6bd36edf55522e2146ce695b2/shell.nix#L19

So upgrading to the new v2 will be beneficial.

**Comment by khuedoan** [comment]
@dotdiego do you have the relevant docs/links? I'm still seeing this [in the most recent devel docs](https://docs.ansible.com/ansible/devel/collections/community/docker/docker_compose_module.html):

> This module requires docker-compose < 2.0.0

**Comment by dotdiego** [comment]
Yes you're right. I didn't understood that PR correctly.
I re-read it and docker_swarm and docker_compose are still using Python SDK until contributions are made to rewrite those modules.
