### ISSUE TITLE
K8s PaaS

### ISSUE THREAD

**Issue by ClashTheBunny** [khuedoan/homelab#85]
It would be nice to have a k8s PaaS. Given the amount of Rancher stuff, like k3s and longhorn, maybe Acorn.io, built by the same folks would be interesting, or one of the other paas in the cncf: https://landscape.cncf.io/card-mode?category=paa-s-container-service&grouping=category

**Comment by khuedoan** [comment]
Thanks, but this is duplicated with https://github.com/khuedoan/homelab/issues/74
