### ISSUE TITLE
PXE Boot / TFTP server

### ISSUE THREAD

**Issue by jrowinski3d** [khuedoan/homelab#89]
### Describe the bug

Not entirely a bug, but maybe more guidance on provisioning bare metal with the `boot.yml` roles in ansible. I can get my local workstation to receive a WoL packet, boot up and wait for a PXE/TFTP server to connect to. My workstation stalls and **times out**. I am wondering if there any other people that also get this result? I used to work with PXE servers when setting DHCP options in the domain controller, but running in a home network I cannot find those options.

- [X] I have read the document

### To reproduce

**dnsmasq.conf**

```bash
# Disable DNS Server.
port=0
# We're DHCP proxying on the network of the host
dhcp-range=192.168.1.71,proxy
pxe-service=X86-64_EFI, "Boot From Network, (UEFI)", grubx64.efi
# Log DHCP queries to stdout
log-queries
log-dhcp
log-facility=-

# Enable TFTP server
enable-tftp
tftp-root=/tftp
```

**grub.conf**

```bash
set timeout=1

menuentry 'ubuntu-20.04.5-live-server-amd64 (PXE)' {
    linux vmlinuz \
        ip=dhcp \
        inst.ks=http://192.168.1.71/init-config/${net_default_mac}.ks
    initrd initrd.img
}
```

### Additional context

My `controller` is running on OSX, and has the IP 192.168.1.71. 

From the workstation, I can telnet to both port 80 and 69 on the `http_1` and `dns_masq` containers.  I had to setup `port-forwarding` on the docker-compose to expose those ports.

**Comment by khuedoan** [comment]
Hi, the controller must run Linux, macOS will not work due to networking limitations (related docs [here](https://homelab.khuedoan.com/installation/production/prerequisites/#initial-controller)).

**Comment by khuedoan** [comment]
Closing due to unsupported OS, please reopen if you still have the issue on Linux.
