### ISSUE TITLE
Have you ever considered moving from k3 to k3os?

### ISSUE THREAD

**Issue by mwasowski** [khuedoan/homelab#91]
First, great work and your setup is really something I hope I can achieve one day (or at least fraction of it) :)

I have a question as title says. Have you ever consider moving from k3 on Rocky Linux to pure k3os and remove one layer of complexity (setting up os and then setting up k3?

Keep up the great work!

Michal

**Comment by khuedoan** [comment]
Yes, I considered it, but [PXE boot is unsupported](https://github.com/rancher/k3os#56). You can read more about other alternatives I considered [here](https://homelab.khuedoan.com/reference/architecture/decision-records/#choosing-the-base-os).

>  I hope I can achieve one day

Btw if you have some x86 machines, you can achieve the same thing relatively quickly because everything is automated :wink:
https://homelab.khuedoan.com/installation

**Comment by khuedoan** [comment]
Closing because the question has been answered and no further action is required.

**Comment by mwasowski** [comment]
@khuedoan Hi, sorry, I've read your message on the go and forgot to apply ._.

Yes, that's a valid reason ;) Though maybe that is not the case anymore?

https://github.com/rancher/k3os/blob/master/README.md#automated-installation

Or you had some issues with this that they do not cover in the readme?

**Comment by khuedoan** [comment]
Oops I sent the wrong link in the previous answer (just updated it), in https://github.com/rancher/k3os/issues/56 looks like it's still not an officially supported way to boot and that there are some rough edges (I can't remember the exact reason, but it didn't work for me when I tried it).

**Comment by mwasowski** [comment]
Sure, no problem :)

Last question. It's not directly related, but why Rocky Linux? It's relatively new (might be called an infant in "Linux world") and I would think that something along CoreOS, Flatcar or something with longer history might be a better pick?

**Comment by mwasowski** [comment]
I know that in a way it's a successor to CentOS, so RHE backend, but still ;)

**Comment by khuedoan** [comment]
It's bug-for-bug compatible with RHEL, so it's basically the same with CentOS. Also I switched to Fedora for a newer kernel.

**Comment by mwasowski** [comment]
Awesome, thanks again!
