### ISSUE TITLE
vault version

### ISSUE THREAD

**Issue by rkoosaar** [khuedoan/homelab#95]
Hi, I noticed that you are using bank-vaults operator. Do you know what version of vault is the operator using?
I noticed that hashicorp has released vault version 1.12.x and somewhere in the bank-vaults config it mentioned vault 1.6.2 I wonder if that is the image version they use or an actual vault version number.

**Comment by khuedoan** [comment]
Yes it's the Vault version https://banzaicloud.com/docs/bank-vaults/operator/upgrade-vault

**Comment by rkoosaar** [comment]
thanks. Just a heads up if you are thinking about upgrading yourself. 
 I've managed to get it working with vault 1.11.5.
 With version 1.12.0 it fails to init and unseal. Not sure how to fix that as of yet.
