### ISSUE TITLE
Question: Partitioning

### ISSUE THREAD

**Issue by Lueton** [khuedoan/homelab#96]
Hey! I saw the partitioning section and have a question, because im really new to this.
```bash
# Partition clearing information
clearpart --all --drives={{ hostvars[item]['disk'] }}
# Partitioning
ignoredisk --only-use={{ hostvars[item]['disk'] }}
partition /boot/efi --fstype=vfat --size=512
partition / --fstype=ext4 --grow
```
If I understand correctly any data is deleted when the operating system is reinstalled. I would like to have the behavior that the OS is deleted and reinstalled on every boot (not part of the question), but data should be retained. To do this I would need two partitions, one that has the OS on it and one that has Kubernetes, etc. on it. Now i only want to erase the OS partition. What would the configuration look like for this?
```bash
# Partition clearing ONLY OS information
clearpart --drives=/os
# Partitioning
partition /boot/efi --fstype=vfat --size=512
partition /os --fstype=ext4 --size=10240
partition / --fstype=ext4 --grow # (if not already exists)
```

**Comment by khuedoan** [comment]
Longhorn will replicate the data across multiple nodes, so if you just want to reinstall one node at a time it should be fine.
If you want a separate partition, you can try modifying the configuration based on https://docs.fedoraproject.org/en-US/fedora/f34/install-guide/appendixes/Kickstart_Syntax_Reference

**Comment by huang12zheng** [comment]
@khuedoan 
I think of a scenario,
The machines are all offline.
1. Should I shutdown PXE and start the machine?
2. Or, change the boot order so that the disk is in front of the network?
